"""user table

Revision ID: 5759e5c6e6ce
Revises: ccb25c21dac0
Create Date: 2019-07-31 12:20:33.361150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5759e5c6e6ce'
down_revision = 'ccb25c21dac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('license', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_dataset_license'), 'dataset', ['license'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_license'), table_name='dataset')
    op.drop_column('dataset', 'license')
    # ### end Alembic commands ###
