"""users table

Revision ID: c29270bfa789
Revises: c2715e9d1cfc
Create Date: 2019-08-09 12:56:39.435978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29270bfa789'
down_revision = 'c2715e9d1cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('tags', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'tags')
    # ### end Alembic commands ###
